Feature pw change
CSW-Study-Group/BOARD pull request #29
Opened 2023-07-25 04:46 UTC by choihb127

비밀번호 변경 기능 완료.
1. profile 페이지에서 비밀번호 변경 페이지 진입
2. 현재 비밀번호, 새로운 비밀번호, 비밀번호 확인 입력 후 제출
3. 새로운 비밀번호, 비밀번호 확인 검사 ( 프론트 스크립트에서 체크 )
4. 기존 비밀번호, 새 비밀번호 백엔드에서 검사 및 변경
5. 변경 성공시 메인페이지로 이동 ( 코드: 200 )
- 비밀번호 오류 ( 코드: 401 )
- 계정 조회 실패 ( 코드: 404 )
- 기타 서비스 에러 ( 코드: 500 )

2023-07-25 11:05 UTC, SoN-B requested changes

2023-07-25 11:05 UTC, SoN-B commented on BackEnd/src/services/user.js
> +  const user = await User.findByPk(user_id); // findeUser로 바꾸는지?
그대로 User.findByPk 사용하셔도 됩니다. 오히려, 서비스 함수들끼리 연관이 되지 않으니 더 좋을 듯합니다.

2023-07-25 11:05 UTC, SoN-B commented on BackEnd/src/routes/user.js
> +  '/profile/change_password',
REST API는 보통 _(underbar) 대신 -(dash)를 사용합니다. 또, patch와 change가 의미가 중복되니, /profile/password로 API 주소를 바꿔주세요. (PATCH /profile/password로 보면 이해되실 겁니다.)

2023-07-25 13:05 UTC, choihb127 commented
API 주소 change_password에서 password로 변경

2023-07-26 09:41 UTC, SoN-B approved these changes

2023-07-26 09:42 UTC, merged